### ISSUE TITLE
Expected tag name after <

### ISSUE THREAD

**Issue by tonyoconnell** [amazingBastard/landing-page-builder#1]
Hello,

On install I receive the following error

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   client/views/admin/admin.html:7: Expected tag name after `<`
   ... data-tab="second"> <<<<<<< HEAD           {{>
   ...
   ^

=> Your application has errors. Waiting for file change.

Any idea what's wrong?

**Comment by dvzrd** [comment]
Hey, yea that was a merge issue. It should be resolved now from the recent commits, try again and let me know if it works.
